In [1]:
import numpy as np

In [2]:
f=np.arange(5,50,10)

In [3]:
f

array([ 5, 15, 25, 35, 45])

In [4]:
#create an numpy arraay

In [5]:
x=np.arange(10)

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[:5]

array([0, 1, 2, 3, 4])

In [9]:
print("every other element",x[::2])

every other element [0 2 4 6 8]


In [10]:
print("every other element starting at index 1",x[1::2])

every other element starting at index 1 [1 3 5 7 9]


In [13]:
print("element in reverse order",x[::-1])

element in reverse order [9 8 7 6 5 4 3 2 1 0]


In [14]:
x=np.array([1,2,3])

In [15]:
x

array([1, 2, 3])

In [17]:
grid=np.array([[4, 5, 6],
              [7, 8, 9]])

In [18]:
grid

array([[4, 5, 6],
       [7, 8, 9]])

In [24]:
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
np.concatenate([x,[1,2,4]])

array([1, 2, 3, 1, 2, 4])

In [32]:
#TO KNOW ABOUT INBUILT FEATURES OF NUMPY JUST NP.TAP
